# Generated by Django 2.2.16 on 2020-09-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
